name: LearningPlugin
version: '${project.version}'
main: me.bombies.learningplugin.LearningPlugin
api-version: '1.20'
authors: [ Ajani Green (bombies) ]
description: This is Ajani's first Spigot plugin
website: https://ajani.me/

commands:
  login:
    description: Login to the server
    usage: /<command>
    aliases: [ signin, logon ]
  suicide:
    description: Kill yourself
    usage: /<command>
    aliases: [ kms, die ]
  fly:
    description: Fly!
    usage: /<command>

permissions:
  learningplugin.*:
    description: Gives a user access to every permission
    children: {
      learingplugin.fly: true
    }
  learningplugin.fly:
    description: Allows a user to fly
