name: LearningPlugin
version: '${project.version}'
main: me.bombies.learningplugin.LearningPlugin
api-version: '1.20'
authors: [Ajani Green (bombies)]
description: This is Ajani's first Spigot plugin
website: https://ajani.me/
