name: LearningPlugin
version: '${project.version}'
main: me.bombies.learningplugin.LearningPlugin
api-version: '1.20'
authors: [ Ajani Green (bombies) ]
description: This is Ajani's first Spigot plugin
website: https://ajani.me/

softdepend: [PlaceholderAPI]

commands:
  login:
    description: Login to the server
    usage: /<command>
    aliases: [ signin, logon ]
  suicide:
    description: Kill yourself
    usage: /<command>
    aliases: [ kms, die ]
  fly:
    description: Fly!
    usage: /<command> [player]
  workbench:
    description: Open a crafting table
    usage: /<command>
    aliases: [ wb, craft ]
  nick:
    description: Nickname yourself or another player
    usage: /<command> [target] nickname
    aliases: [ nickname ]
  setspawn:
    description: Set the spawn for the server
    usage: /<command>
  spawn:
    description: Teleport to the server spawn
    usage: /<command>
  worlds:
    description: View and manage server worlds
    usage: /<command> [options]
  menu:
    description: Open a custom menu
    usage: /<command>
  invsee:
    description: View another player's inventory.
    usage: /<command> player
  teleportbow:
    description: Gives a user a teleport bow
    usage: /<command> [players]
    aliases: [ tpbow ]
  godhorse:
    description: Spawn a God Horse.
    aliases: [ ghorse, gh ]
  chatcolor:
    description: Changes the chat color of the player
    aliases: [ color, colour, chatcolour ]
  holograms:
    description: View and manage holograms
    aliases: [ hologram, holo ]
  sign:
    description: Create a sign??
  ping:
    description: Check your ping
  randomteleport:
    description: Teleport to a random location
    aliases: [ rtp, randomtp ]
  nuke:
    description:  Give yourself a nuke
  gameend:
    description: Test custom events
  spawner:
    description: Give yourself a spawner
permissions:
  learningplugin.*:
    description: Gives a user access to every permission
    children:
      learingplugin.fly.*: true
      learingplugin.nick.*: true
      learningplugin.spawn.set: true
      learningplugin.invsee.*: true
  learningplugin.fly.*:
    description: Gives a user access to all fly permissions
    children:
      learningplugin.fly: true
      learningplugin.fly.others: true
  learningplugin.fly:
    description: Allows a user to fly
  learningplugin.fly.others:
    description: Allows a user to toggle fly for other users
  learningplugin.nick.*:
    description: Gives a user access to all nick permissions
    children:
      learningplugin.nick: true
      learningplugin.nick.others: true
  learningplugin.nick:
    description: Allows a user to nickname themselves
  learningplugin.nick.others:
    description: Allows a user to nickname other users
  learningplugin.spawn.set:
    description: Allows a user to set the server spawn
  learningplugin.spawn:
    default: true
    description: Allows a user to teleport to the server spawn
  learningplugin.worlds.*:
    description: Gives a user access to all world permissions
    children:
      learningplugin.worlds.view: true
      learningplugin.worlds.create: true
  learningplugin.worlds.view:
    description: Allows a user to view the server worlds
  learningplugin.worlds.create:
    description: Allows a user to create a new world
  learningplugin.invsee.*:
    description: Gives a user access to all invsee permissions
    children:
      learningplugin.invsee: true
      learningplugin.invsee.move: true
  learningplugin.invsee:
    description: Allows a user to view another player's inventory
  learningplugin.invsee.move:
    description: Allows a user to move items in another player's inventory
  learningplugin.teleportbow:
    description: Allows a user to get a teleport bow
  learningplugin.teleportbow.others:
    description: Allows a user to give another user a teleport bow
  learningplugin.godhorse:
    description: Allows a user to spawn a God Horse
  learningplugin.chatcolor.red:
    description: Allows a user to change their chat color to red
  learningplugin.chatcolor.darkred:
    description: Allows a user to change their chat color to dark red
  learningplugin.chatcolor.gold:
    description: Allows a user to change their chat color to gold
  learningplugin.chatcolor.yellow:
    description: Allows a user to change their chat color to yellow
  learningplugin.chatcolor.green:
    description: Allows a user to change their chat color to green
  learningplugin.chatcolor.darkgreen:
    description: Allows a user to change their chat color to dark green
  learningplugin.chatcolor.aqua:
    description: Allows a user to change their chat color to aqua
  learningplugin.chatcolor.darkaqua:
    description: Allows a user to change their chat color to dark aqua
  learningplugin.chatcolor.blue:
    description: Allows a user to change their chat color to blue
  learningplugin.chatcolor.darkblue:
    description: Allows a user to change their chat color to dark blue
  learningplugin.chatcolor.purple:
    description: Allows a user to change their chat color to purple
  learningplugin.chatcolor.darkpurple:
    description: Allows a user to change their chat color to dark purple
  learningplugin.chatcolor.black:
    description: Allows a user to change their chat color to black
  learningplugin.holograms:
    description: Allows a user to view and manage holograms
