name: LearningPlugin
version: '${project.version}'
main: me.bombies.learningplugin.LearningPlugin
api-version: '1.20'
authors: [ Ajani Green (bombies) ]
description: This is Ajani's first Spigot plugin
website: https://ajani.me/

commands:
  login:
    description: Login to the server
    usage: /<command>
    aliases: [ signin, logon ]
  suicide:
    description: Kill yourself
    usage: /<command>
    aliases: [ kms, die ]
  fly:
    description: Fly!
    usage: /<command> [player]
  workbench:
    description: Open a crafting table
    usage: /<command>
    aliases: [ wb, craft ]
  nick:
    description: Nickname yourself or another player
    usage: /<command> [target] nickname
    aliases: [ nickname ]

permissions:
  learningplugin.*:
    description: Gives a user access to every permission
    children:
      - learingplugin.fly.*
      - learingplugin.nick.*
  learningplugin.fly.*:
    description: Gives a user access to all fly permissions
    children:
      - learningplugin.fly
      - learningplugin.fly.others
  learningplugin.fly:
    description: Allows a user to fly
  learningplugin.fly.others:
    description: Allows a user to toggle fly for other users
  learningplugin.nick.*:
    description: Gives a user access to all nick permissions
    children:
      - learningplugin.nick
      - learningplugin.nick.others
  learningplugin.nick:
    description: Allows a user to nickname themselves
  learningplugin.nick.others:
    description: Allows a user to nickname other users
