name: LearningPlugin
version: '${project.version}'
main: me.bombies.learningplugin.LearningPlugin
api-version: '1.20'
authors: [ Ajani Green (bombies) ]
description: This is Ajani's first Spigot plugin
website: https://ajani.me/

commands:
  login:
    description: Login to the server
    usage: /<command>
    aliases: [ signin, logon ]
  suicide:
    description: Kill yourself
    usage: /<command>
    aliases: [ kms, die ]
  fly:
    description: Fly!
    usage: /<command> [player]
  workbench:
    description: Open a crafting table
    usage: /<command>
    aliases: [ wb, craft ]
  nick:
    description: Nickname yourself or another player
    usage: /<command> [target] nickname
    aliases: [ nickname ]
  setspawn:
    description: Set the spawn for the server
    usage: /<command>
  spawn:
    description: Teleport to the server spawn
    usage: /<command>
permissions:
  learningplugin.*:
    description: Gives a user access to every permission
    children:
      learingplugin.fly.*: true
      learingplugin.nick.*: true
      learningplugin.spawn.set: true
  learningplugin.fly.*:
    description: Gives a user access to all fly permissions
    children:
      learningplugin.fly: true
      learningplugin.fly.others: true
  learningplugin.fly:
    description: Allows a user to fly
  learningplugin.fly.others:
    description: Allows a user to toggle fly for other users
  learningplugin.nick.*:
    description: Gives a user access to all nick permissions
    children:
      learningplugin.nick: true
      learningplugin.nick.others: true
  learningplugin.nick:
    description: Allows a user to nickname themselves
  learningplugin.nick.others:
    description: Allows a user to nickname other users
  learningplugin.spawn.set:
    description: Allows a user to set the server spawn
  learningplugin.spawn:
    default: true
    description: Allows a user to teleport to the server spawn
